Repository Islandora-Devops/isle-buildkit, pull requests merged in 2022-05, with the labels that each got.

#206 Issue 174 - Logging
  activemq/Dockerfile
  activemq/README.md
  activemq/rootfs/etc/confd/conf.d/log4j.properties.toml
  activemq/rootfs/etc/confd/templates/log4j.properties.tmpl
  activemq/rootfs/etc/cont-init.d/02-activemq-setup.sh
  alpaca/README.md
  alpaca/rootfs/etc/confd/templates/org.ops4j.pax.logging.cfg.tmpl
  alpaca/rootfs/etc/cont-init.d/04-alpaca-setup.sh
  base/rootfs/etc/cont-init.d/00-tty.sh
  blazegraph/README.md
  blazegraph/rootfs/etc/cont-init.d/03-blazegraph-setup.sh
  blazegraph/rootfs/opt/tomcat/webapps/bigdata/WEB-INF/classes/log4j.properties
  download/rootfs/usr/local/bin/create-service-user.sh
  fcrepo/rootfs/etc/cont-init.d/03-fcrepo-setup.sh
  fcrepo/rootfs/opt/tomcat/bin/setenv.sh
  fcrepo6/rootfs/etc/cont-init.d/03-fcrepo-setup.sh
  fcrepo6/rootfs/opt/tomcat/bin/setenv.sh
  fits/Dockerfile
  fits/README.md
  fits/rootfs/etc/confd/conf.d/log4j.properties.toml
  fits/rootfs/etc/confd/templates/log4j.properties.tmpl
  fits/rootfs/etc/cont-init.d/03-fits-setup.sh
  karaf/README.md
  karaf/rootfs/etc/confd/conf.d/config.properties.toml
  karaf/rootfs/etc/confd/conf.d/org.ops4j.pax.logging.cfg.toml
  karaf/rootfs/etc/confd/templates/config.properties.tmpl
  karaf/rootfs/etc/confd/templates/org.ops4j.pax.logging.cfg.tmpl
  karaf/rootfs/etc/cont-init.d/03-karaf-startup.sh
  nginx/rootfs/etc/cont-init.d/02-ngnix-install.sh
  solr/Dockerfile
  solr/README.md
  solr/rootfs/etc/confd/conf.d/log4j.properties.toml
  solr/rootfs/etc/confd/templates/log4j.properties.tmpl
  tomcat/Dockerfile
  tomcat/README.md
  tomcat/rootfs/etc/confd/templates/server.xml.tmpl
Labels: release

#212 Adding testing isle-buildkit doc
  docs/maintainers/testing_process.md
Labels: documentation, release

#143 No longer use volume for Matomo install
  matomo/Dockerfile
  matomo/README.md
  matomo/rootfs/etc/cont-init.d/00-container-environment-01-set-subsite-defaults.sh
  matomo/rootfs/etc/cont-init.d/00-matomo-deploy.sh
  matomo/rootfs/etc/cont-init.d/03-matomo-setup.sh
Labels: matomo, release
